### ISSUE TITLE
No GPL please!

### ISSUE THREAD

**Issue by pulsejet** [DevCom-IITB/instiapp-flutter#2]
This effectively makes it impossible to use on iOS, as the App Store is incompatible with GPL. A few options:
1) A permissive license - Apache/MIT
2) Weak copyleft - I've used MPL 2.0 for the [angular app](https://github.com/pulsejet/iitb-app-angular) for this purpose (was looking into NativeScript back then). This is still somewhat of a gray zone, but [OSSE hints](https://opensource.stackexchange.com/questions/1762/is-the-mozilla-public-license-compatible-with-apples-app-store) we should be fine with it.
3) Dual licensing - I've zero experience with this, but it should work too.

**Comment by tastelessjolt** [comment]
I don't know much about licencing, I just used what was used in the original InstiApp. And it seemed good enough. Anyway, I'm changing it to MIT. Though, I don't know exactly what it means. I'll close this when I merge some commits to master prior to adding the MIT licence.
