### ISSUE TITLE
[EventPage] Adds 'Add to Calendar' integration

### ISSUE THREAD

**Issue by tastelessjolt** [DevCom-IITB/instiapp-flutter#25]
Replicate of https://github.com/wncc/InstiApp/pull/286

- [x] Android
  - [x] Fix manifest permissions
- [x] iOS
  - [x] Fix manifest permissions

**Comment by tastelessjolt** [comment]
Overall working is fine now. 

- [ ] Add error handling when a calendar is deleted
- [ ] Add setting in SettingsPage to clear `don't ask again` defaults

**Comment by VIBR0X** [comment]
events are added to calendar by default
