### ISSUE TITLE
Change map url to map.insti.app

### ISSUE THREAD

**Issue by pulsejet** [DevCom-IITB/instiapp-flutter#26]
Title says it all. This gives me better control on caching etc.

Hopefully we'll have a native implementation anyway 😛

**Comment by tastelessjolt** [comment]
Actually, I thought of including the InstiMap webapp in the App itself and it's actually included and it's working but it has an older version where there's some bug in the UI. But updating it would be a problem. What do you think?

**Comment by pulsejet** [comment]
That'll be best, cause I don't think it'll be updated too often, and a native implementation would need an update for each change anyway.

**Comment by tastelessjolt** [comment]
Added the pulsejet/instimapweb-standalone in the app itself.
