### ISSUE TITLE
Automatically select hostel in mess menu.

### ISSUE THREAD

**Issue by kumarrahul33** [DevCom-IITB/instiapp-flutter#33]
Problem: We have to go to the mess menu and select the hostel every time to see the menu. This is a cumbersome task to do and can be avoided.

Suggested Solution: The hostel info can be automatically selected.

**Comment by VIBR0X** [comment]
The hostel info is fetched automatically form [link](https://gymkhana.iitb.ac.in/profiles/user/). Update the profile there
