### ISSUE TITLE
Buy&Sell: Loading Posts

### ISSUE THREAD

**Issue by VIBR0X** [DevCom-IITB/instiapp-flutter#46]
When the posts are loading, the text is loaded first and the images later.
Create a loading animation which pops up before the posts and images are loaded.

**Comment by namritaansh02** [comment]
Does this refer to the activity when all the scroll page is opened, wherein the image will show devcom logo until intended image loaded or is it referring to the page when we click on a particular buynsell post?

**Comment by VIBR0X** [comment]
On the posts page (image attached for reference) 
![bns](https://github.com/DevCom-IITB/instiapp-flutter/assets/44766005/54f35023-4622-4b80-b67a-644705be5a70)
Instead of this blank screen there should be a loader

**Comment by Prayas-Agrawal** [comment]
Done. Please Check #59
